tagFormat: '${version}'
branches:
  - name: main
  - name: develop
    prerelease: true
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/npm'
  - '@semantic-release/git'
  - '@semantic-release/github'
  - - '@saithodev/semantic-release-backmerge'
    - branches:
        - develop
      backmergeStrategy: merge
      allowSameBranchMerge: true
